package ch.bfh.bti7081.s2018.green.designs;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.Button;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.TextArea;
import com.vaadin.ui.TextField;
import com.vaadin.ui.declarative.Design;

/** 
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class DiagnosisDesign extends HorizontalLayout {
	private TextArea textFieldResult;
	private TextField textFieldName;
	private Button btnSetName;

	public DiagnosisDesign() {
		Design.read(this);
	}

	public TextArea getTextFieldResult() {
		return textFieldResult;
	}

	public TextField getTextFieldName() {
		return textFieldName;
	}

	public Button getBtnSetName() {
		return btnSetName;
	}
}
