package ch.bfh.bti7081.s2018.green.designs;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.Button;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.declarative.Design;

/** 
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class NavigationDesign extends HorizontalLayout {
	protected Button navBtnMedication;
	protected Button navBtnJournal;
	protected Button navBtnTherapy;
	protected Button navBtnDiagnosis;

	public NavigationDesign() {
		Design.read(this);
	}
}
